apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp-demo-helm
  namespace: openshift-gitops
spec:
  destination:
    namespace: avp-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml
    repoURL: 'https://github.com/dlystra/argocd-vault-plugin.git'
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
