apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm/templates
    plugin:
      name: argocd-vault-plugin
    repoURL: 'https://github.com/dlystra/argocd-vault-plugin.git'
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
