---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-sa-cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: openshift-gitops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-edit
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit