kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault
  namespace: vault
  annotations:
    openshift.io/host.generated: 'true'
spec:
  path: /
  to:
    kind: Service
    name: vault
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
