apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avp-demo-kustomize
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: avp-demo
  project: default
  source:
    repoURL: 'https://github.com/dlystra/argocd-vault-plugin.git'
    targetRevision: main
    path: kustomize/overlays/demo
    plugin:
      name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true